"""rename fiel

Revision ID: a2a7abefc7aa
Revises: 05a09ae18368
Create Date: 2022-03-08 00:36:27.469151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a7abefc7aa'
down_revision = '05a09ae18368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
