"""add category field & table

Revision ID: bf37ecde804d
Revises: 77f446125447
Create Date: 2022-03-21 21:31:27.872020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf37ecde804d'
down_revision = '77f446125447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.add_column('cars_info', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cars_info', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars_info', type_='foreignkey')
    op.drop_column('cars_info', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
