"""add gearBox table -> change car model

Revision ID: 05a09ae18368
Revises: a8af936a8a4d
Create Date: 2022-03-08 00:25:51.330791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a09ae18368'
down_revision = 'a8af936a8a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gearbox_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gearbox_name')
    )
    op.add_column('cars_info', sa.Column('gearbox_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cars_info', 'gear_box', ['gearbox_id'], ['id'])
    op.drop_column('cars_info', 'gear_box_auto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_info', sa.Column('gear_box_auto', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cars_info', type_='foreignkey')
    op.drop_column('cars_info', 'gearbox_id')
    op.drop_table('gear_box')
    # ### end Alembic commands ###
