"""remove unique from car.link

Revision ID: 77f446125447
Revises: f9d37c113d84
Create Date: 2022-03-08 18:11:14.037635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f446125447'
down_revision = 'f9d37c113d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_info_link_key', 'cars_info', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cars_info_link_key', 'cars_info', ['link'])
    # ### end Alembic commands ###
