"""add last page of ads for parse

Revision ID: cbc2b08a748b
Revises: fc7a9a20997e
Create Date: 2022-03-07 20:50:29.978292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc2b08a748b'
down_revision = 'fc7a9a20997e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_last_page',
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('page_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_last_page')
    # ### end Alembic commands ###
