"""add table for unfined brand|models

Revision ID: f9d37c113d84
Revises: a2a7abefc7aa
Create Date: 2022-03-08 14:39:07.265358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d37c113d84'
down_revision = 'a2a7abefc7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unfinded_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_data', sa.String(), nullable=True),
    sa.Column('additional_data', sa.String(), nullable=True),
    sa.Column('data_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unfinded_data')
    # ### end Alembic commands ###
